GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/5ff46db62113a9f8cdbdec79

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "040-123456"
}